language: groovy
rvm:
- 1.8.8
install:
- gradle build
before_script:
- gradle test
- export PLUGIN_VERSION=${TRAVIS_COMMIT:0:7}
script:
- gradle -PpluginVersion=${PLUGIN_VERSION}
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
notifications:
  slack:
    secure: xdWzUHa7JiICHUMMikGY/pxJPJe6hAGxGphp7EuPL1SQYgXmlZzvQVqVGtFyiEPWaCTeMG6s1S+0oqeKTfja8fnI5F6zHSNRuBce2Gc5ElNXrf4xZlhHCh8m0SGnF/+DPy8BgV6dPwAvNnIY3deP3iL91rXPVaOIZ9mg75V5zMizXcgMdll4yQ592guphG1mQDhyZErs+8jojQ7wkNuDZ6vBwJDOuAtBhYj2fHunnQtDEWfxWofqXB0GkfneCxk7YlOO0XxUMI3k4rna0UElQ9lobzvkbzhf2i96t28qrA+kIeS8PV89BU/qZh3kL5p2V2YZyszpadKaM8Rjz3nL4NN//l3hfPTHeDAL0xhz6a6ESG4ahgkwSvATXTERoErGoAJMQzUtRipVOZVFKZIRZQ50FbJpPxthbpUvliGHY+i3sqpNbaDWnW6lfl09xfC8B3jUAv5iU6H5elZnPjtnHaQhKjwguzv0xj9Fg79QSAYaRXmr6ZV0Jt4d9aE/TrlHLtqWEbrjiOevLuyWNy1BkAb0XdwnyxtAF9T6Lolg21NvxSk1vGwh/Hiqvh1ET+qDBi+wyO+p6pxmsx/vHC1gQE1O/KSeEmSUcwimFJju+5qJQtwbGMBJ1pXu7s+GjHwHWskiAAblDs6N1FldnhxRPvLeUsipXRtfKh48qraXTds=
    on_success: change
    on_failure: change
  email: false
deploy:
  provider: releases
  api_key:
    secure: e5Vh46RBDoME2GbWGUUnGc48pSCXaUEamuo98WjsA8Fi9yyIvTukwnwuoMjcEEu/v5f9UVb9l6RGtAjJHckt3HS65jPELZEkPw6w0WH1YIa/8rle3pzyTMczxCrtlHv+s0Q/giXxVOg2Eb0sB74m6T/s4cE5yJ8ksTUNsfdW+1uAATkUF4EVqVQKULvx/w68Q/7VtEdWtmch6MUyWW9dEcP2Pn08Oc/y0pqOOBhT1GHcaHg4tDCuoObWtut8Yy5nfSPxP+gxcCTnahn6nVA5z+gvyibBA5jQnTsOLYCuycpGx/qmfwZaBcj8hG79Ftgo5U1wAIMg61c7ceHDghTELWdM5mV3h2v6OFPLnoNCqsRytKLuW19eNN8jKHKdeCDvfhzcPgRmNBeDTku407t2PyU5YZ3kAHJCMWuz52hZo8m0Z2Jv2d2aUO52GaBoAsoFqddpJY2fAwlI17Nl6ok4mdMOdyKHQ6f/4R2krugtaNkCbLkBw8Z3Hw2SMYIoE23ANB/E5u/9yHwIJiofNqWZRP2M/CwqbE3XUm2AXFsFGCWmREwOKLtL1XwNVN1FNnKPzTu8OtTMZNMH9sE0Aqy1Dy1okv7yRDbsWeA9jqhz5PmMj8RpU78iJhODC/ugP0TmGAADzf4PO+GmeU8VPJQ1ImbevPeaNbs1CvY6yGyBlPo=
  file_glob: true
  file: build/distributions/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: IBM-UrbanCode/Gradle-UCB
